### ISSUE TITLE
Y axis distance

### ISSUE THREAD

**Issue by MasseyAlbany** [Pwdr/Pwdr-Model-0.1#33]
Hi,

I am having issues while testing with the distances traveled, specifically by the Y axis. When I press print, it starts printing at the zero position (where it is when power is connected). It prints the first layer fine, but then when it goes to spread a new layer it goes all the way to the end and then jams against the edge. This means that either it is set to move too far or I am doing something wrong in my set up before I press print.

Please help me

**Comment by Pwdr** [comment]
Just to check: do you perform the correct homing procedure? Step 1: move
carriage to far end (by hand, no power) Step 2: enable power, click 'Home'
in the GUI.

If you've done that, and the carriage still jams the other end, then adjust
the following parameters:

const long build_piston_length = 28000/stepY;
const long distance_roller_nozzle = 30000;
const long build_piston_end_stop = 76000;

**Comment by MasseyAlbany** [comment]
Do you mean the "initial position" button? If I press that after connecting the power the head moves along the Y axis about 85% of the way (to the left). Then when I press "print file" it starts printing and moving the Y axis, still moving to the left. This means it jams while trying to print the file because it only has a small amount of movement before it hits the end. However if I do not press the "initial position" button, it starts printing where it is, and moves to the left. Even if I start it at the right end, so that it has the entire length to move, it still jams when doing a new layer.

I will have a play with the code you mention above and see what happens with the distances traveled.
