### ISSUE TITLE
Usage of firmware, please help me out

### ISSUE THREAD

**Issue by Casssss** [Pwdr/Pwdr-Model-0.1#38]
Hello,

I have been trying to find the right software to operate a pwdr inkjet printer and translate a .stl file to readable instructions. The printer consists of 5 stepper motors (X, Y, Z, Z2, Roller). I am using an Arduino MEGA 2560. I am completely new to this and am still trying to become familiar with the language. 

So the firmware2_0 file does not include the rest of the arduino files. Which of these do I need for operating the motors and how do I combine them into uploadable firmware?

Also does anyone have a reccomendation on which slicer to use? 

Any help is greatly appreciated.

**Comment by Pwdr** [comment]
Hi Casssss,

Most questions will propably be answered as soon as you read through the
user manual: http://pwdr.github.io/usermanual.html

**Comment by Casssss** [comment]
Thanks for the quick response. I figured most of it out now.
